# Generated by Django 4.0.1 on 2022-01-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_currency_language_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='symbol',
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
