# Generated by Django 4.0.1 on 2022-02-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_roomtype_bed_alter_room_room_type_and_more'),
        ('frontdesk', '0004_alter_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.roomtype'),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
