# Generated by Django 4.0.1 on 2022-02-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=256),
            preserve_default=False,
        ),
    ]
