# Generated by Django 4.0.1 on 2022-02-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_hotel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='floor_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='floor',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='sort_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
