# Generated by Django 4.0.1 on 2022-02-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_floor_name_floor_name_floor_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('hotel', 'sort_id')},
        ),
    ]
