# Generated by Django 4.0.1 on 2022-02-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_floor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='manager.hotel'),
        ),
    ]
