# Generated by Django 4.0.1 on 2022-02-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_owner_hotel_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('beds', models.JSONField()),
                ('room_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('has_air_con', models.BooleanField(default=False, verbose_name='A/C')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='wifi')),
                ('has_tv', models.BooleanField(default=False, verbose_name='TV')),
                ('has_fridge', models.BooleanField(default=False, verbose_name='fridge')),
                ('has_hot_water', models.BooleanField(default=False, verbose_name='hot water')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='manager.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('is_general', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='manager.hotel')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.roomtype'),
        ),
    ]
