# Generated by Django 4.0.1 on 2022-02-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_roomtype_bed_alter_room_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='manager.hotel'),
        ),
    ]
