# Generated by Django 4.0.1 on 2022-02-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_bed_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
