# Generated by Django 4.0.1 on 2022-02-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_roomtype_beds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='beds',
        ),
        migrations.CreateModel(
            name='RoomBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.bed')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.roomtype')),
            ],
        ),
    ]
