# Generated by Django 4.0.1 on 2022-02-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_remove_roomtype_beds_roombed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='vacansy',
            new_name='vacancy',
        ),
    ]
