# Generated by Django 4.0.1 on 2022-02-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_room_floor_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cleaning_status',
            field=models.CharField(choices=[('C', 'Clean'), ('D', 'Dirty')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='vacancy',
            field=models.CharField(choices=[('V', 'Vacant'), ('O', 'Occupied')], default='V', max_length=1),
        ),
    ]
