# Generated by Django 4.0.1 on 2022-02-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['sort_id']},
        ),
    ]
